### ISSUE TITLE
Missing token error

### ISSUE THREAD

**Issue by ordinarygulp** [datagutten/TIDAL-to-musicbrainz#1]
Running the command as in the usage, `php submit_isrc.php 3acf6bc2-417b-43e2-90f4-68c84120658f https://listen.tidal.com/album/102255200`, I get the error:
`Missing token`

Additionally, running the batch command produces:
```
php batch_submit_isrc.php df388c49-15e0-498b-a122-af32a947d8a5
PHP Warning:  Invalid argument supplied for foreach() in /home/b1kr0se/TIDAL-to-musicbrainz/batch_submit_isrc.php on line 2
```

**Comment by datagutten** [comment]
I found a new way to fetch tokens from TIDAL and after some rewriting it works again.
